#!/usr/bin/env python3
"""Generate a ~1000-figure stress-test .tex file for the simple-wrap package."""

import random
import os

OUTPUT_PATH = "/home/z/my-project/src/simple-wrap/test-stress.tex"
NUM_FIGURES = 1000
LIPSUM_MAX = 150  # lipsum package provides paragraphs 1–150

# Color bases and opacity ranges for fake figures
COLOR_BASES = [
    "red", "blue", "green", "orange", "purple", "cyan",
    "yellow", "magenta", "teal", "violet", "brown", "lime",
    "pink", "olive", "navy", "maroon", "aqua", "fuchsia",
]

random.seed(42)  # Reproducible output


def random_color():
    base = random.choice(COLOR_BASES)
    opacity = random.randint(10, 60)
    return f"{base}!{opacity}"


def random_size():
    """Return (width_cm, height_cm) as floats with 1 decimal."""
    w = round(random.uniform(3.0, 6.0), 1)
    h = round(random.uniform(2.0, 10.0), 1)
    return w, h


def random_lipsum_range():
    """Return a lipsum range string with 2-3 paragraphs.
    
    Cycle through the 150 paragraphs so the whole document uses varied text.
    We return something like 'lipsum[42-44]'.
    """
    n_paras = random.randint(2, 3)
    start = random.randint(1, LIPSUM_MAX)
    end = min(start + n_paras - 1, LIPSUM_MAX)
    return f"lipsum[{start}-{end}]"


def main():
    lines = []

    # ── Preamble ──────────────────────────────────────────────────
    lines.append(r"% test-stress.tex — Stress test for simple-wrap.sty")
    lines.append(r"% Compile: lualatex test-stress.tex")
    lines.append(r"% Generated by generate-stress.py")
    lines.append(r"\documentclass[11pt,a4paper]{article}")
    lines.append(r"\usepackage{lipsum}")
    lines.append(r"\usepackage{caption}")
    lines.append(r"\usepackage{xcolor}")
    lines.append(r"\usepackage{simple-wrap}")
    lines.append(r"")
    lines.append(r"\begin{document}")
    lines.append(r"")
    lines.append(r"\section*{Simple-Wrap Stress Test}")
    lines.append(r"This document contains %d figures for stress testing the simple-wrap package." % NUM_FIGURES)
    lines.append(r"")

    # ── Generate figures ───────────────────────────────────────────
    for i in range(1, NUM_FIGURES + 1):
        color = random_color()
        w, h = random_size()
        lipsum = random_lipsum_range()

        lines.append(r"%% ── Figure %d ──" % i)
        lines.append(r"\begin{simplewrap}")
        lines.append(r"  \textcolor{%s}{\rule{%.1fcm}{%.1fcm}}" % (color, w, h))
        lines.append(r"  \captionof{figure}{Fig %d: %.1fx%.1fcm}" % (i, w, h))
        lines.append(r"\end{simplewrap}")
        lines.append(r"\simplewrapnext %s" % lipsum)
        lines.append(r"")

        # Occasionally insert an extra paragraph between figures to
        # increase page-break diversity
        if random.random() < 0.2:
            extra_lipsum = random_lipsum_range()
            lines.append(r"%s" % extra_lipsum)
            lines.append(r"")

    lines.append(r"\end{document}")
    lines.append("")

    # ── Write file ────────────────────────────────────────────────
    content = "\n".join(lines)
    os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
    with open(OUTPUT_PATH, "w") as f:
        f.write(content)

    print(f"Generated {OUTPUT_PATH}")
    print(f"  Total figures: {NUM_FIGURES}")
    print(f"  Total lines:   {len(lines)}")
    print(f"  File size:     {len(content):,} bytes")


if __name__ == "__main__":
    main()
